apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: office-pvc
  namespace: office-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: office-storage
  resources:
    requests:
      storage: 5Gi
